### ISSUE TITLE
Normalization issue

### ISSUE THREAD

**Issue by elbfox** [dams-mcda/Dams-MCDA#104]
Normalization in WSM miscalculating for Ind_DamsDataMatrix columns: 1 (fish biomass) and 4 (annuitized cost), potentially others. minimization working properly in columns 5, 6, maximization working properly in 2, 3, etc. Column 1 and 4 are not working, to the best of my knowledge. 

In the normalization process, **Ind_DamsDataMatrix --> Ind_NomalizedMatrix,** ALL normalized data values should be between 0 and 1.  Column 1 (fish biomass) shows values >1, while column 4 (annuitized cost) does not have enough variation (i.e., all values are too close to 1)

Observed while working in branch: GraphTesting in file WSM_graphs_test.R

**Comment by sythel** [comment]
fixed in SimplifyNormalization, reopen if needed
