### ISSUE TITLE
add f_nrge.RData to tracking

### ISSUE THREAD

**Issue by sythel** [dams-mcda/Dams-MCDA#112]
branch GraphChecking:
>shiny_server_1  | Warning in file(filename, "r", encoding = encoding) :
shiny_server_1  |   cannot open file 'f_nrge2.RData': No such file or directory
shiny_server_1  | Warning: Error in file: cannot open the connection
shiny_server_1  |   56: file
shiny_server_1  |   55: source

**Comment by elbfox** [comment]
I added it to GraphChecking just now.
