### ISSUE TITLE
WSM output image map

### ISSUE THREAD

**Issue by sythel** [dams-mcda/Dams-MCDA#118]
https://github.com/dams-mcda/Dams-MCDA/blob/b18b9a7b910448dfb5f30511529c4a4f6eb430ce/src/dams_mcda/WSM_graphs_test.R#L378

why is fname a list 995 long?

**Comment by elbfox** [comment]
Ah, it's not supposed to be. The print function gives the top pick, so this is what I have done locally (haven't pushed these changes yet):

fname <- sprintf('maps/Penobscot_MO_14_%d.png',idxRank[[1]])
map_num <-(fname[1])
print(map_num)

**Comment by elbfox** [comment]
I'm having to rewrite all of those files I added this morning, so this change will be coming in an hour or so. Feel free to add it yourself if you need it before then. Sorry about the holdup...have some recalculations on DamsData.csv to make sure all my GHG emissions values are updated.

**Comment by sythel** [comment]
we can do fname <- sprintf('maps/Penobscot_MO_14_%d.png',idxRank[1,1])
and that seems to work
