### ISSUE TITLE
Additional: Directional links

### ISSUE THREAD

**Issue by elbfox** [dams-mcda/Dams-MCDA#122]
Include a "Go Back" link at the top of each page, and a "Next" link at the bottom of each page.

These links should move the user ahead to the next tab or back to the previous tab in the order they appear on the sidebar  (E.g. West Enfield "Next" link would take the user to Medway, and "Go Back" link would take the user from West Enfield to "Step 2: View Existing Dams Map".

EDIT: this type of link would also be helpful to have if someone accidentally clicks "upload preferences". If it is easy to add a back link, please do.

**Comment by elbfox** [comment]
This would actually be helpful to have working for the workshop so I'm removing the "low priority" tag.

**Comment by sythel** [comment]
mostly working, adding style to buttons now

**Comment by sythel** [comment]
8a37452 button style
