### ISSUE TITLE
Dam Results Tab downloads

### ISSUE THREAD

**Issue by elbfox** [dams-mcda/Dams-MCDA#124]
Download button on individual dam results tab (e.g. West Enfield Results) currently doesn't download as any particular type of file (e.g., not a csv). 

Will also want users to have the option to download graphs as .PNG images.

**Comment by sythel** [comment]
do we want the download for each dam to be a subset of the combined results? Don't know how helpful this would be.

I will look into graph downloading

**Comment by elbfox** [comment]
Yes, we want the download to be the WeightedResults level specific to each dam, with the summed score tacked on as the final column.  It should be a 5X15 matrix, with an MCDA score (summed score) for each decision alternative in column 15.

**Comment by sythel** [comment]
Weighted Results with Total Column added

**Comment by sythel** [comment]
Graphs downloadable

**Comment by elbfox** [comment]
Can you please make the multi-dam results table, graphs, map downloadable, too?

**Comment by sythel** [comment]
map done, graphs that exist done

multi dam tables need input see #135

**Comment by elbfox** [comment]
Can we close this issue? Sharon says all download buttons seem to work on the live version.

**Comment by elbfox** [comment]
Need download buttons for ALL of the tables on the individual dam results pages (e.g. Tables 1 - 3 on West Enfield Results tab) as well as the first graph (e.g. Figure 5, raw prefs graph on West Enfield Results tab).

Sharon also says there is an issue with the download button at the bottom of the West Enfield Results tab. She gets this result: 

![image](https://user-images.githubusercontent.com/19410104/65638970-34d59d00-dfb5-11e9-9f6d-ef4d2ba4b55c.png)

**Comment by sythel** [comment]
@elbfox  Table 1. is same as the download button at the bottom, should we move button or have duplicate?

**Comment by elbfox** [comment]
All download buttons should be immediately below the things (figures, tables) they download. 

No duplicates necessary.

**Comment by elbfox** [comment]
Do we now have the

> download buttons for ALL of the tables on the individual dam results pages (e.g. Tables 1 - 3 on West Enfield Results tab) as well as the first graph (e.g. Figure 3, raw prefs graph on West Enfield Results tab).

?
