### ISSUE TITLE
Slider update problem specific to PR #125

### ISSUE THREAD

**Issue by elbfox** [dams-mcda/Dams-MCDA#126]
In the CombinedPreferenceOutput branch (see #125), when I click "Update" on any individual dam page after moving slider bar settings, the app shuts down. There are no error codes so I am not sure what is happening. I put a note there about the error, too. 

I'm hoping it's just an indentation problem that's confusing the button --> output functionality.

**Comment by sythel** [comment]
haven't experienced this. indentation won't cause syntax problems in this language as far as i know

**Comment by elbfox** [comment]
i know only enough Shiny to get myself into trouble. I'm getting an error when I update any dam criteria sliders.

**Comment by elbfox** [comment]
Could it be because I rearranged the multi-dam output tabs to show up before the single dam output tabs in the ui.R script?

**Comment by elbfox** [comment]
This is what is happening before it kicks me out: 
update button 1
------------------
BarPlot title: Raw Preference Scores for West Enfield Dam
data: c(50, 30, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10)c(7, 13, 12, 3, 4, 10, 2, 5, 8, 9, 6, 1, 11, 14)
#(values in data): 2
classtype: data.frame
datatype: list
#(x names): 14
------------------
------------------
BarPlot title: Weighted sum MCDA scores, West Enfield Dam
data: c(50, 30, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10)c(7, 13, 12, 3, 4, 10, 2, 5, 8, 9, 6, 1, 11, 14)
#(values in data): 2
classtype: data.frame
datatype: list
#(x names): 5
------------------
Warning: Error in paste0: cannot coerce type 'closure' to vector of type 'character'
  78: paste0
  74: updateDamGraph [C:\Users\Owner\Documents\Beatrice2\R_ELF\R_NEST\MCDA_App_Shiny\MCDA_06262019\src\dams_mcda/server.R#510]
  73: updateDam1 [C:\Users\Owner\Documents\Beatrice2\R_ELF\R_NEST\MCDA_App_Shiny\MCDA_06262019\src\dams_mcda/server.R#654]
  72: observeEventHandler [C:\Users\Owner\Documents\Beatrice2\R_ELF\R_NEST\MCDA_App_Shiny\MCDA_06262019\src\dams_mcda/server.R#1551]

**Comment by sythel** [comment]
error is server.R line 630

**Comment by sythel** [comment]
updateDam1/update button 1 is called when preferences for dam1 == 100 and he update button is clicked

**Comment by sythel** [comment]
I was planning on making methods generateDam1... generateDam8 to generate plots/tables that rely on data from WSM

**Comment by sythel** [comment]
server.R line 510

there is no variable a
```
output[[paste0("WSMPlot", damId, a)]] <- renderBarPlot( 
```

**Comment by elbfox** [comment]
Yes, error is line 630. I'm hoping I have this figured out now...I didn't realize that you were no longer using WSM_graphs_test.R (oops!) and wrote the individual dam tables into there to make sure everything was looking good. I have pulled them into the WSM.R script now. These can be removed later if that cleans things up...I know you were working on tables and while I don't want to duplicate efforts, I do need to do some table & graph comparisons here to make sure everything is calculating correctly for the individual dams. 

I will comment out that output for now with the a.

**Comment by elbfox** [comment]
Yes, output[[paste0("WSMPlot", damId, "a")]] is right

**Comment by sythel** [comment]
closing
