### ISSUE TITLE
Application Flow: Generate WSM related output

### ISSUE THREAD

**Issue by sythel** [dams-mcda/Dams-MCDA#127]
potential update: only have one generate button instead of one for each dam and the combined

**Comment by elbfox** [comment]
sounds good, but I agree, low priority right now. It seems like the issues I'm (still) experiencing there are caused by something else, but definitely do trigger on the update. Now, I have dams 1 - 7 working, with dam 8 being the one that generates the error. Looking into this.

**Comment by sythel** [comment]
only generate needed as of now is the combined results,
could look into generating once the total preference selection is 100% so no button click is needed

**Comment by elbfox** [comment]
Please go ahead with this change. I think it makes sense to include for the Workshop.

**Comment by sythel** [comment]
thoughts on Previous/Next Buttons?
