### ISSUE TITLE
Data Upload rows?

### ISSUE THREAD

**Issue by elbfox** [dams-mcda/Dams-MCDA#132]
How many rows is the upload preferences dataset supposed to have? I thought 8, but I get an error when I try to load my TestData.csv. I took out the header with the criteria (column) names, too, so it's just the data values. 

![image](https://user-images.githubusercontent.com/19410104/65081583-efd8b780-d971-11e9-82f1-94c04a193342.png)

**Comment by elbfox** [comment]
Realizing the live version is old (which was my screenshot above), but the local version I have (up to date now with the master) also gave an error (no code or explanation, it just didn't let me press "continue"). @sythel please update the live version when possible. The sooner I can get Sharon's thoughts on it's current status, the better.

**Comment by sythel** [comment]
deployed branch IndividualDamOutput on server

**Comment by elbfox** [comment]
Thank you. I'll let Sharon know. How many rows, cols is the app expecting the upload preferences dataset to have?

**Comment by sythel** [comment]
```
required_rows <- 8                                                                                
required_cols <- 15 # includes dam names in first row
```
the download file found on combined results page (just re-added now; guessing it was missed in the merge)

**Comment by elbfox** [comment]
I get a different error when I include the dam names. It says: 

> Scores do not total correctly, Invalid File.. Please verify you are uploading the correct file or try a different file.

![image](https://user-images.githubusercontent.com/19410104/65177109-10614a00-da24-11e9-8cf2-52745b2b2ad5.png)

This is the file I'm using (have tried both .csv and .xlsx versions). Am I missing something?
[TestData_forLiveSite.xlsx](https://github.com/dams-mcda/Dams-MCDA/files/3627936/TestData_forLiveSite.xlsx)

**Comment by sythel** [comment]
it only supports csv at the moment

**Comment by sythel** [comment]
oh get rid of the sum row

**Comment by elbfox** [comment]
Right, I did that to check and included it to show you. I actually didn't include the sum column it when I tried.

**Comment by sythel** [comment]
debugging now

**Comment by sythel** [comment]
problem is your file is 0 -> 1 instead of preferences being 0 -> 100

**Comment by sythel** [comment]
which do we want to stick with for input/output 1 or 100

**Comment by elbfox** [comment]
OH! I feel so dumb. Thank you. No need to change anything...I'll fix my file and try again

**Comment by elbfox** [comment]
We want to make sure dams are in the following order (ordered by latitude):

West Enfield Dam
Medway Dam
East Millinocket Dam
Dolby Dam
North Twin Dam
Millinocket Development
Millinocket Lake Dam
Ripogenus Dam

**Comment by sythel** [comment]
the file should change automatically, as its written in order of dams

**Comment by elbfox** [comment]
Perfect. Closing again.
