### ISSUE TITLE
Mapped output --> test to confirm that it matches expectations

### ISSUE THREAD

**Issue by elbfox** [dams-mcda/Dams-MCDA#136]
EDIT: Multi-dam result maps do not generate as one might expect. For instance, with extreme preferences, like 100% toward any given criterion, the result is strange (like improve hydropower at most, remove some, and keep one for fish preferences). 

TESTING: 
(1) @sythel  you mentioned at some point that you needed to test the mapped output...is this like No. 3 (see below), or did you have something else in mind?
(2) @elbfox to check that local version selection matches live version selection
(3) @elbfox and @sythel to test a few different preferences to see if the dam decision numbers (e.g.  0=keep and maintain) match what appears on the map (i.e., is the right map being selected)

**Comment by sythel** [comment]
same issue as I am dealing with in #137
