### ISSUE TITLE
Tables/graphs cleanup

### ISSUE THREAD

**Issue by elbfox** [dams-mcda/Dams-MCDA#146]
**Sig figs/rounding**
Reduce sigfigs on all tables and graphs to 2-3 max (e.g. 1.1 or 1.12). 

Absolutely NO decimals for MCDA scores (e.g. Ind_WeightedScoreMatrix) or raw preference scores (e.g. RawCriteriaMatrix) – that implies a level of certainty we definitely do not have.

**Summed scores in Weighted Score Tables**
Weighted Score table(s) on the webpage (e.g. Table 4, West Enfield) doesn't show the total summed score but the download does. Can you please add the summed score as a column at the end @sythel?

@elbfox to make all changes in Sharon's notes document

**Comment by elbfox** [comment]
Also @sythel please add numbers to the tops of the bars for the new Figure 1 graph in West Enfield and all other dams (I am updating and re-labeling these now to all be labeled Figure 1 for ease of troubleshooting until we are mostly done). 

**User-defined preference scores graphs**
Please add to this graph an x-axis scale of 100 to be consistent with slider bars. Is it possible to change color scheme to be consistent with the other graphs? (like a gradation, not colors ordered randomly)

**Comment by elbfox** [comment]
@sythel please also adjust the colors of the segments in the top 5 scenario graph in Step 4: Combined Results to indicate the decision alternatives at each dam, not the dam itself. For instance, West Enfield might be yellow in one scenario, and green in another scenario. 

![image](https://user-images.githubusercontent.com/19410104/65820541-74d89200-e1f8-11e9-85a3-0080fae1fd19.png)

**Comment by elbfox** [comment]
Labels should have both the dam and decision alternative, like WestEnfield-Remove or Ripogenus-KeepMaintain

**Comment by sythel** [comment]
> Summed scores in Weighted Score Tables
Weighted Score table(s) on the webpage (e.g. Table 4, West Enfield) doesn't show the total summed score but the download does. Can you please add the summed score as a column at the end @sythel?

done 

>@sythel please also adjust the colors of the segments in the top 5 scenario graph in Step 4: Combined Results to indicate the decision alternatives at each dam, not the dam itself. For instance, West Enfield might be yellow in one scenario, and green in another scenario.

done

**Comment by sythel** [comment]
>Also @sythel please add numbers to the tops of the bars for the new Figure 1 graph in West Enfield and all other dams (I am updating and re-labeling these now to all be labeled Figure 1 for ease of troubleshooting until we are mostly done).

done

**Comment by sythel** [comment]
>User-defined preference scores graphs
Please add to this graph an x-axis scale of 100 to be consistent with slider bars. Is it possible to change color scheme to be consistent with the other graphs? (like a gradation, not colors ordered randomly)

assuming this is figure 3

**Comment by elbfox** [comment]
yes, the name should be "user-defined preference scores" and was the raw preferences graph pulling from the slider bars (formerly Fig. 5 in live version, which is a few updates old)

**Comment by sythel** [comment]
> User-defined preference scores graphs
Please add to this graph an x-axis scale of 100 to be consistent with slider bars. Is it possible to change color scheme to be consistent with the other graphs? (like a gradation, not colors ordered randomly)

done

issue potentially closed

**Comment by elbfox** [comment]
Can you add it to the live version so I can check it, first? Is this solved? I think I may have addressed it in ResultsIssueFixes but I made a note there that I wasn't able to check it locally because the server wouldn't load

**Comment by sythel** [comment]
@elbfox lets finish PR #152 and I will PR also, then will launch a new live version

 I did some rounding but didn't want conflicts with your rounding so its hard to say

**Comment by elbfox** [comment]
adding this final commit and then we can finish PR #152

**Comment by sythel** [comment]
fig 1 still missing rounding adding now

**Comment by elbfox** [comment]
For all tables and raw pref. figures (now numbered 3 in each dam results page of live version)
> Sig figs/rounding
> Reduce sigfigs on all tables and graphs to 2-3 max (e.g. 1.1 or 1.12).
> 
> Absolutely NO decimals for MCDA scores (e.g. Ind_WeightedScoreMatrix) or raw preference scores (e.g. RawCriteriaMatrix) – that implies a level of certainty we definitely do not have.
Current figure 1 does not have bar labels at all (please add, @sythel)
![image](https://user-images.githubusercontent.com/19410104/65957485-f3147e80-e41a-11e9-8aca-0ef6772d2daa.png)

**Comment by elbfox** [comment]
Sharon says: Please remove all decimals everywhere (except for Tables 3 & 4 in individual results, which should only have 2 sigfigs max)

**Comment by elbfox** [comment]
Also:  It's difficult to see which segment of each bar corresponds to which item from the legend in Figures 1 and 3 of combined results. Is it possible to list the decision alternative/dam combinations for each scenario in a table below the figure as well? If we keep the multi-dam results, we need people to be able to be able to easily tell what the actual decision alternatives are for each dam for the top-ranked scenarios.

**Comment by sythel** [comment]
> 
> 
> Also: It's difficult to see which segment of each bar corresponds to which item from the legend in Figures 1 and 3 of combined results. Is it possible to list the decision alternative/dam combinations for each scenario in a table below the figure as well? If we keep the multi-dam results, we need people to be able to be able to easily tell what the actual decision alternatives are for each dam for the top-ranked scenarios.

not too sure how to address this.
I just made changes so that legend appear more reliably on the graph [preview](https://imgur.com/a/h3cPmpa)

**Comment by elbfox** [comment]
I think the issue is that the colors seem linked with the unique combination of dam-alternative, which is what we asked for, but now that we can see it in practice, it doesn't quite give the clarity we were looking for. So, I think if the colors were matched with the dams, and the labels were matched with the dam-alternative combination, that would help interpret Figure 1. For Figure 3, 

Additionally (or perhaps instead of this change, reverting back to the original Figure 1) it may help to have a table below the figure with the dam and the decision alternative. Kind of like what we print in scoresum_index in the WSM.R but with the alternative names instead of codes.

**Comment by elbfox** [comment]
Scenarios are out of order again, too. 

![image](https://user-images.githubusercontent.com/19410104/66003849-34397c80-e475-11e9-889a-568992b9888e.png)

Is there a way to put the dam-alternative specific label on the actual bar, like you have with the value? So it could say Medway-Remove (63) or something?

**Comment by sythel** [comment]
> Scenarios are out of order again, too.

due to rounding the parts vs the actual total

474.79 | 4.00 | 2.00 | 3.00 | 3.00 | 2.00 | 2.00 | 2.00 | 2.00 | 740.00
474.45 | 2.00 | 2.00 | 4.00 | 3.00 | 2.00 | 4.00 | 2.00 | 2.00 | 362.00
471.96 | 4.00 | 2.00 | 4.00 | 4.00 | 2.00 | 3.00 | 2.00 | 2.00 | 747.00
471.42 | 2.00 | 2.00 | 4.00 | 3.00 | 2.00 | 2.00 | 2.00 | 2.00 | 355.00
470.89 | 2.00 | 2.00 | 3.00 | 4.00 | 2.00 | 2.00 | 2.00 | 2.00 | 357.00

**Comment by sythel** [comment]
just pushed some debug tables under that specific graph to the live server

**Comment by elbfox** [comment]
I can see how the rounding the parts could lead to this difference in values (what I'm understanding is that the top scenario output is still the top scenario, it's just the label that is off). The problem that is bigger is that the top 5 scenarios here don't match the top 5 mapped output at all (see #151). This is _the_ output of the model, so while we should keep working to get it up and running (because we want to have this in the final version available on the DDC), it's not something we are going to be able to fix before the workshop on Thursday, at this point. I need to spend all of tomorrow planning the facilitation, working on presentations, and pulling the multi-dam stuff out of the model on a dedicated branch.

**Comment by elbfox** [comment]
@sythel Use original dam-specific color scheme for Combined Output Figure 1. Include table with list of dams and decision alternatives for top 5 scenarios (label rows/columns accordingly) and include text in the caption about how to use both (@elbfox to do). @elbfox to edit caption to Fig 3 to tell people to look at Table 4 from the Individual results for any given dam to see what the criteria are if they can’t tell from the color scheme on the figure.

**Comment by sythel** [comment]
> original dam-specific color scheme for Combined Output Figure 1

confused about this. Is this referring to figure 1 on shiny2.gsscdev.com or the v2.0.0 version

**Comment by elbfox** [comment]
Figure 1 on the live version (v2.0.0). So, this is now a low-priority issue, because it is in the MOGA version. Sorry, my mistake for flagging it as important right now! We need to focus on no-MOGA version stuff.
