### ISSUE TITLE
zip file of all downloadable items

### ISSUE THREAD

**Issue by elbfox** [dams-mcda/Dams-MCDA#149]
It would be nice to include a tab at the end where the user can download everything as a zip file 'package' of their individual tables and graph results for all dams, as well as the multi-dam one and the map recommendation. This is low priority and on hold until after the workshop. Nice to have but not critical.

**Comment by sythel** [comment]
I have made progress but I think its not going to be user-friendly to use as it takes a long time to generate

**Comment by sythel** [comment]
one graph for each dam alone takes almost 20 seconds to generate

**Comment by elbfox** [comment]
You're right. This is too long. Thank you for looking into it. I think if you could focus instead on #146, #182 , #183 so we make sure to have consistent and quality downloads for what we already have, that is preferable.
