### ISSUE TITLE
East Millinocket strange graph issue

### ISSUE THREAD

**Issue by elbfox** [dams-mcda/Dams-MCDA#150]
There is a problem with the East Millinocket graphs in Figs. 1 and 2, where the improve hydro values are lower than they should be and the improve fish passage values are higher than they should be. Using the Equal preferences file (attached but in csv format), my Excel file (also attached) checks out for all other graphs. 
[EqualPrefs_forLiveSite.xlsx](https://github.com/dams-mcda/Dams-MCDA/files/3659971/EqualPrefs_forLiveSite.xlsx)
[MCDA_Check_CalcsGraphsEQUAL092519 (2).xlsx](https://github.com/dams-mcda/Dams-MCDA/files/3659972/MCDA_Check_CalcsGraphsEQUAL092519.2.xlsx)
Live app multi-dam results:
![image](https://user-images.githubusercontent.com/19410104/65726187-7aac6700-e082-11e9-859e-ce7752c167fe.png)
Excel multi-dam results (individual dams calculated from DamsData.csv and equal prefs file above, not the 995 scenario dataset):
![image](https://user-images.githubusercontent.com/19410104/65726344-da0a7700-e082-11e9-876e-f6243ed471b2.png)

The strange thing is that the Weighted Scores are consistent across the app and the Excel File. 

![image](https://user-images.githubusercontent.com/19410104/65728035-99f9c300-e087-11e9-9024-b41073ac6cbd.png)
![image](https://user-images.githubusercontent.com/19410104/65728059-b0a01a00-e087-11e9-8bf9-142987b0a3fb.png)

So, I think the problem is in whatever fix you are trying to do in the graph. I think we only need this "rules" catch for the multi-dam part. It appears to be layering on top of the fix I added back in the NormalizationChanges branch (WSM.R):

````
	Ind_NormalizedMatrix[2:5,6,3] <- c(1,1,1,1)#This replaces properties NaN at East Millinocket
	Ind_NormalizedMatrix[1,1,2] <- 1 #This replaces fish habitat NaN at Medway
	Ind_NormalizedMatrix[5,3,1:3] <- 1#This replaces the reservoir storage NaN at West Enfield, Medway, East Millinocket
	Ind_NormalizedMatrix[1,2,7] <- 1 #This replaces the river rec NaN at Millinocket Lake
	
````

**Comment by elbfox** [comment]
Sharon pointed out this also appears to be happening for Ripogenus. The value is slightly off for improve fish passage as well (58 vs 60). I haven't checked the WeightedResults yet to see for sure if the problem is the same.

**Comment by sythel** [comment]
> The strange thing is that the Weighted Scores are consistent across the app and the Excel File

seems like numProperties is not consistent

**Comment by sythel** [comment]
and its normalized value in figure 11 is 0 for numProperties

**Comment by sythel** [comment]
server.R is using f_nrge2 but it seems f_nrge maybe was updated more recently, which should we use?

**Comment by elbfox** [comment]
> @elbfox server.R is using f_nrge2 but it seems f_nrge maybe was updated more recently, which should we use?

It doesn't matter at this point because Sam will be updating on Monday after he runs the MOGA. Use f_nrge if you want the more updated.

**Comment by sythel** [comment]
Table 10. numProperties is 0 as well. maybe issue is DamsData is the issue?

**Comment by elbfox** [comment]
No, it's the normalization again because the data values are 0 for all num properties. This should fix numProperties for East Millinocket.
````
	Ind_NormalizedMatrix[2:5,6,3] <- c(1,1,1,1)#This replaces properties NaN at East Millinocket
	Ind_NormalizedMatrix[1,1,2] <- 1 #This replaces fish habitat NaN at Medway
	Ind_NormalizedMatrix[5,3,1:3] <- 1#This replaces the reservoir storage NaN at West Enfield, Medway, East Millinocket
	Ind_NormalizedMatrix[1,2,7] <- 1 
````
Is your 'rules' catch happening for these individual dams? It shouldn't be. I think we have to be weirdly specific here in the normalization, so I'm not sure there is anything better than a static fix at this point.

**Comment by sythel** [comment]
@elbfox yes that fix does get E.Milli to the values matching to the excel graphic

**Comment by elbfox** [comment]
Good. Thanks for checking. @sythel can you just confirm for me that you've taken the 'rules' part out for graphs for individual dam results?

**Comment by sythel** [comment]
I have not yet; rules are only applied to specifically to Figure 2. will remove them if you still request

**Comment by elbfox** [comment]
I'm confused, I thought they were for addressing the normalization weirdness (because some of the dams have 0 values for all decision alternatives) for the multi-dam dataset?

**Comment by sythel** [comment]
nope

**Comment by sythel** [comment]
> Sharon pointed out this also appears to be happening for Ripogenus. The value is slightly off for improve fish passage as well (58 vs 60). I haven't checked the WeightedResults yet to see for sure if the problem is the same.

ripos value change is probably from rounding; compared from Table 32 and your excel sheet tab(Weighted_Norm_DamsData)

**Comment by sythel** [comment]
issue possibly closed?

**Comment by elbfox** [comment]
Thanks for clarifying. I definitely thought you were doing something different! It all makes sense now. 

I think we can close this issue.
