### ISSUE TITLE
summed score problem 

### ISSUE THREAD

**Issue by elbfox** [dams-mcda/Dams-MCDA#153]
scoresum_total is different from the corresponding scenario score in the Combined Results page. @sythel do you have thoughts about this?

**Comment by elbfox** [comment]
![image](https://user-images.githubusercontent.com/19410104/65896610-84341880-e37b-11e9-9a2a-0521e783ddfb.png)
^summed score on my laptop

![image](https://user-images.githubusercontent.com/19410104/65896861-0ae8f580-e37c-11e9-9e8c-9935b27d9036.png)
^Scenario 1 score is very different from the laptop score

**Comment by sythel** [comment]
haven't experienced this yet, is this from branch ResultsIssueFix

**Comment by elbfox** [comment]
Yes, in WSM_graphs_test.R. Haven't multiplied NormalizedMatrix by 100, so that's part of it. But, the reason this issue came up is that Medway's 4.714 score is weird for the multi-dam scenario graph. Why so low? It is 100 for remove on the aggregated individual dam results graph (this is using 
[FishPrefs_forLiveSite.xlsx](https://github.com/dams-mcda/Dams-MCDA/files/3672271/FishPrefs_forLiveSite.xlsx)
 prefs)
![image](https://user-images.githubusercontent.com/19410104/65898151-e3dff300-e37e-11e9-845c-80ead01050ac.png)

**Comment by elbfox** [comment]
Okay, fixed some things locally. Was missing 
```````````
TestMatrix <- NormalizedMatrix
TestMatrix[1,,] <- NormalizedMatrix[4,,]
TestMatrix[2,,] <- NormalizedMatrix[7,,]
TestMatrix[3,,] <- NormalizedMatrix[6,,]
TestMatrix[4,,] <- NormalizedMatrix[5,,]
TestMatrix[5,,] <- NormalizedMatrix[8,,]
TestMatrix[6,,] <- NormalizedMatrix[3,,]
TestMatrix[7,,] <- NormalizedMatrix[2,,]
TestMatrix[8,,] <- NormalizedMatrix[1,,]
NormalizedMatrix <- TestMatrix*100 # multiply by 100 to be consistent with app
message("size of NormalizedMatrix", dim(TestMatrix))
``````````
in WSM_graphs_test.R before, sums now look like this: 

![image](https://user-images.githubusercontent.com/19410104/65900567-4687bd80-e384-11e9-9f4c-00a1ab7caacf.png)

**Comment by elbfox** [comment]
accidental issue closure...sorry!

**Comment by sythel** [comment]
```
TestMatrix <- NormalizedMatrix
TestMatrix[1,,] <- NormalizedMatrix[4,,]
TestMatrix[2,,] <- NormalizedMatrix[7,,]
TestMatrix[3,,] <- NormalizedMatrix[6,,]
TestMatrix[4,,] <- NormalizedMatrix[5,,]
TestMatrix[5,,] <- NormalizedMatrix[8,,]
TestMatrix[6,,] <- NormalizedMatrix[3,,]
TestMatrix[7,,] <- NormalizedMatrix[2,,]
TestMatrix[8,,] <- NormalizedMatrix[1,,]
NormalizedMatrix <- TestMatrix*100 # multiply by 100 to be consistent with app
message("size of NormalizedMatrix", dim(TestMatrix))
```

the one above may be wrong try using this instead

```
# Normalized is 4 7 6 5 8 3 2 1
# target is     1 2 3 4 5 6 7 8
TestMatrix <- NormalizedMatrix
TestMatrix[1,,] <- NormalizedMatrix[8,,]
TestMatrix[2,,] <- NormalizedMatrix[7,,]
TestMatrix[3,,] <- NormalizedMatrix[6,,]
TestMatrix[4,,] <- NormalizedMatrix[1,,]
TestMatrix[5,,] <- NormalizedMatrix[4,,]
TestMatrix[6,,] <- NormalizedMatrix[3,,]
TestMatrix[7,,] <- NormalizedMatrix[2,,]
TestMatrix[8,,] <- NormalizedMatrix[5,,]
NormalizedMatrix <- TestMatrix
```

**Comment by elbfox** [comment]
![image](https://user-images.githubusercontent.com/19410104/65902275-07f40200-e388-11e9-940f-37beb52c05c6.png)
This actually gets us a result inconsistent with the live version
![image](https://user-images.githubusercontent.com/19410104/65902320-24903a00-e388-11e9-82d4-e0f7a12af423.png)

**Comment by elbfox** [comment]
And the scoresum_total value is still a mismatch.

**Comment by elbfox** [comment]
solved

![image](https://user-images.githubusercontent.com/19410104/65903660-cb75d580-e38a-11e9-8114-efcdeb084594.png)

**Comment by sythel** [comment]
nice, is that using first or second NormalizationMatrix re-ordering?

**Comment by elbfox** [comment]
Second? I think!

**Comment by elbfox** [comment]
So the problem now is that we're pretty sure we're normalizing differently in the multi-dam dataset than the ind-dam dataset...confirming with Sam and coding a potential secondary normalization for another graph in the multi-dam combined results page.

**Comment by sythel** [comment]
correct, ind-dam uses Ind_NormalziedMatrix which uses min/max values to normalize
when multi-dam uses the sourced f_nrge file

**Comment by elbfox** [comment]
Yes, I'm working on a secondary normalization across all _dams_ for the individual dams results, so that we can make a new graph helping to explain the differences between the multi-dam results and the individual dam results. Waiting on confirmation from Sam that this is what is going on in his MOGA model. If this isn't it, and the updated dataset isn't it (the cause of the mismatch), then we may need to pull the multi-dam results from the model altogether. This would be really, really tragic.

**Comment by elbfox** [comment]
UPDATE: 1412 scenarios, so given 14 criteria, there will be 14*1412 = 19768 columns

Still working on matching individual results to multi-dam results. This issue is very related to #151 at this point

**Comment by elbfox** [comment]
Closing, because it is part of #151.
