### ISSUE TITLE
hydro prefs crash dev site

### ISSUE THREAD

**Issue by elbfox** [dams-mcda/Dams-MCDA#162]
uploading the attached file as a csv crashes the dev site won't generate results (screen goes gray and asks you to reload the page), but the preferences load in fine. 
[HydroPrefs_forLiveSite.xlsx](https://github.com/dams-mcda/Dams-MCDA/files/3676717/HydroPrefs_forLiveSite.xlsx)

**Comment by sythel** [comment]
looking into it now

**Comment by sythel** [comment]
due to update of dam_names removing "Dam" from  "Medway Dam" fix incoming

**Comment by sythel** [comment]
@elbfox live on site, had to delete all saved runs due to the dam_names update

**Comment by elbfox** [comment]
Thank you for your speedy response on this! I'll let Sharon know.
