### ISSUE TITLE
Group mode doesn't appear to work

### ISSUE THREAD

**Issue by elbfox** [dams-mcda/Dams-MCDA#163]
For testing I signed up as a new user associated with Group 1 (Sharon did this too), and upload preferences ( ), while Sharon uploaded preferences ( ), both in csv format, then saved, generated, and saved again. Then, I refreshed the page and tried to use group mode (should have averaged Sharon's and my preferences), but the slider bars didn't move and nothing is marked "complete". Sharon did the same, but instead logged out and logged in before trying to use group mode, with similar results where sliders are set at 0 and nothing is marked "complete".

**Comment by sythel** [comment]
it works for me, it doesn't mark step 3 tabs as complete as I assumed we wanted the user to still manually edit each

**Comment by sythel** [comment]
upload data does not work with group mode

**Comment by elbfox** [comment]
Right, so if I went in and uploaded data (which is more or less individual mode), saved my generated results, and then refreshed the page, it lets me pick group mode and then at that point shouldn't the group mode be averaging the individual results?

**Comment by sythel** [comment]
you saved in individual mode so it if you pick individual mode it will load it, group mode will only load results made in group mode

**Comment by elbfox** [comment]
I think we have had a miscommunication about this, and I apologize for that. The way Sharon and I were expecting this to work was:
(1) individual log in with an account and associate with a group
(2) use app in individual mode, save preferences
(3) when user goes to see group mode, they would see the averaged values for anyone associated with the group saving in individual mode
No. 3 is the point where at the workshop, we would log in and use group mode, with averaged values, and then discuss as a group whether those values look right to them, based on their own understanding of the issues and preferences, or if the values need to change. Then, slider bars could be moved from the default (individual average) position. 

Is this still workable? Or is there another way I should be thinking about running the group activity? If individuals are using in group mode, will their user saves just overwrite each other? Or will the flow I've outlined above work, just that folks need to be in group mode, rather than individual mode?

**Comment by sythel** [comment]
> If individuals are using in group mode, will their user saves just overwrite each other?

No

The current way it works is using group mode for part 2 

The difference is for part2 currently they would see current groups inputs as placeholders for sliders

I can change it to match your expectations

**Comment by elbfox** [comment]
Yes, I think if you changed it to match Sharon's and my expectations that would be best

> (1) individual log in with an account and associate with a group
> (2) use app in individual mode, save preferences
> (3) when user goes to see group mode, they would see the averaged values for anyone associated with the group saving in individual mode

I'm expecting to log in myself in group mode and see the average, to show up on a projector screen, so everyone can see the same screen and we discuss together.  I don't know that the current set up for part 2 makes sense because there are no group inputs before individuals use the tool, so having group input as a  placeholder for the slider just sets them all at 0, the same way they are for the individual model. And, it seems like the individual results are stuck in individual mode the way it's currently organized.

**Comment by sythel** [comment]
done, will be in next PR

**Comment by elbfox** [comment]
Thank you! I'll keep an eye out for it.

**Comment by elbfox** [comment]
Sharon says:  "now, when I am in the new login I created to test the group mode, it won't let me do Individual Preferences. When I click on Individual Preferences nothing happens. If I use the other login I was using before that doesn't have a group associated with it, Individual Preferences works fine."

**Comment by sythel** [comment]
> Sharon says: "now, when I am in the new login I created to test the group mode, it won't let me do Individual Preferences. When I click on Individual Preferences nothing happens. If I use the other login I was using before that doesn't have a group associated with it, Individual Preferences works fine."

PR #165  might fix; however I was able to use indiv mode as a user with a group before

**Comment by elbfox** [comment]
Ok this seems to work now. Closing.
