### ISSUE TITLE
New version launched

### ISSUE THREAD

**Issue by sythel** [dams-mcda/Dams-MCDA#168]
After PR #166 #167 we will want to review the website

newest master branch live on server

**Comment by elbfox** [comment]
![image](https://user-images.githubusercontent.com/19410104/65993514-67711100-e45f-11e9-8168-8eeee051a7d5.png)
Scenario with highest score should be top. Why does scenario 3 have the highest score? Maybe issue #153 again?

**Comment by elbfox** [comment]
![image](https://user-images.githubusercontent.com/19410104/65993684-b454e780-e45f-11e9-95b9-a9499a42eb74.png)

Combined multi-dam results page Fig. 2 has visible axes but the other figs do not

**Comment by sythel** [comment]
due to the theme, Fig 2. looked more confusing with the theme that doesnt have axis lines

**Comment by elbfox** [comment]
Can we be consistent with the other figs and give them axis lines?

**Comment by sythel** [comment]
> Scenario with highest score should be top. Why does scenario 3 have the highest score? Maybe issue #153 again?

this looks like something else im looking into it

**Comment by elbfox** [comment]
Just crashed when I tried EqualPrefs

**Comment by sythel** [comment]
PR #169

**Comment by sythel** [comment]
> Can we be consistent with the other figs and give them axis lines?
PR #170

**Comment by sythel** [comment]
new version up with past two PRs

**Comment by elbfox** [comment]
Upload no longer works in live version

**Comment by sythel** [comment]
just worked for me

**Comment by sythel** [comment]
make sure to clear cache

**Comment by sythel** [comment]
@elbfox PR #171 live on server

**Comment by elbfox** [comment]
Thank you, Billy, for all of the work you did today on this! I think we need to plan to create a separate version (branch? whatever is live) without the MOGA. I am going to start that locally on my computer tonight. We can't get any of the results to match and it's just not OK to do a workshop without a working model. So, we want to keep the MOGA (multi-dam) version somewhere, to try to work through these bugs (perhaps with help from Sam) after the workshop, but time has run out on this thing to get it all working. I am facilitating on Thursday with Sharon, so I need to prep for that as well, and I am going to need most of tomorrow to do that.
