### ISSUE TITLE
Mobile version of site

### ISSUE THREAD

**Issue by elbfox** [dams-mcda/Dams-MCDA#175]
Mobile version of the site doesn't let user scroll down (using iPhone and Safari). It was awkward on iPhone/Safari in the past (like waaay back in March for the student test workshop and last version of this app) but functional. It does load on the iPhone/Safari page but since I can't scroll down, I can't actually use the slider bars in the mobile version.

**Comment by sythel** [comment]
>   Mobile version of the site doesn't let user scroll down (using iPhone and Safari). It was awkward on iPhone/Safari in the past (like waaay back in March for the student test workshop and last version of this app) but functional. It does load on the iPhone/Safari page but since I can't scroll down, I can't actually use the slider bars in the mobile version.


these work for android, and just tested on iphone 10

**Comment by sythel** [comment]
From PR but should of said it here
> seems iphone 7 should have iOS 13 so it should be the same as iphone 11

**Comment by sythel** [comment]
can you confirm your ios version
