### ISSUE TITLE
User preferences Figure 1 improvements

### ISSUE THREAD

**Issue by elbfox** [dams-mcda/Dams-MCDA#184]
Related to #146 

Is there any way to display the user preferences graph (Fig 3, individual dam results in step 5) with an x-axis scale of 100?  It would be more consistent with the slider bars. 

![image](https://user-images.githubusercontent.com/19410104/66484663-6484aa80-ea75-11e9-9ee0-6a9024190e36.png)
(example above axis is out of 7, should be out of 100)

Why don’t the decision criteria colors appear in the same order as the multi-dam results, with that gradation effect? They are kind of all randomly distributed.

**Comment by sythel** [comment]
PR #186
