### ISSUE TITLE
File input for individual results

### ISSUE THREAD

**Issue by sythel** [dams-mcda/Dams-MCDA#190]
Re order application init modal, adding upload of data for indiv/group

old method
----------
[modal 1](https://github.com/dams-mcda/Dams-MCDA/blob/0e438ffe0a0f179e9648429129283f7126e16187/src/dams_mcda/server.R#L346). choose indiv/group/upload data

new method
----------
modal 1. choose indiv/group

modal 2. upload or skip

**Comment by elbfox** [comment]
cannot upload csv file anymore for some reason
![image](https://user-images.githubusercontent.com/19410104/82922425-946eb880-9f47-11ea-8584-62b066ed8b8d.png)

**Comment by elbfox** [comment]
Ok this is an issue with both the dam names column and without in the csv file, both with my laptop as the server and the shiny2 version. The upload functionality used to work, and I haven't changed any of the related code.

**Comment by elbfox** [comment]
> Ok this is an issue with both the dam names column and without in the csv file, both with my laptop as the server and the shiny2 version. The upload functionality used to work, and I haven't changed any of the related code.

Update: upload functionality does not work in 'live' shiny2 version, but the individual input does (move slider bars each time to test). In the local version with my updates, neither works, so something I did must have impacted this function. Troubleshooting this issue within the WSM.R now.

**Comment by sythel** [comment]
upload functionality worked for me (shiny2.gsscdev.com) can you email me the csv file you were having problems with?

**Comment by elbfox** [comment]
I see what I did wrong. I tried to get rid of 2 decision criteria (move from 14 to 12) and then use the same test files on the shiny2 version (which I see now obviously wouldn't work). The problem is locally in the new DDST_v4 branch since I'm trying to cut down the set of decision criteria and everywhere else dimensions are specified from 14 to 12 columns.

**Comment by elbfox** [comment]
And, also:  `The following objects are masked from ‘package:shiny’:

   ` dataTableOutput, renderDataTable`

**Comment by sythel** [comment]
> 
> 
> And, also: `The following objects are masked from ‘package:shiny’:
> 
> ` dataTableOutput, renderDataTable`

this is a warning not an error

**Comment by elbfox** [comment]
Hmm. I thought it might be related to why my local version was throwing an error but it looks like I resolved it somehow. The app now works in my local version if I input the individual preferences using the slider bars, but the upload file function still isn't working. Continuing to troubleshoot.

**Comment by sythel** [comment]
added new modals in PR #197 

potentially can close this issue after PR is merged

moving file upload problem into a new issue. #196

**Comment by elbfox** [comment]
Is this one that can be closed now?
