### ISSUE TITLE
invalid session 

### ISSUE THREAD

**Issue by sythel** [dams-mcda/Dams-MCDA#192]
temporary solution

clear browser and reload page

**Comment by elbfox** [comment]
This issue presents even when using laptop as the server (i.e., if I launch the app from R)

**Comment by sythel** [comment]
this will occur if there is no django server running to validate/save/load the user session. Which is probably the case if you are just running shiny/R.

potential fix:
could try and add an "Offline Mode" which would skip saving of user sessions. this would remove the ability to load/save runs.

**Comment by sythel** [comment]
closing in favor of #194 

reopen if needed
