### ISSUE TITLE
Django-less "offline" mode

### ISSUE THREAD

**Issue by sythel** [dams-mcda/Dams-MCDA#194]
for ease of development remove hard dependency of django. will still allow file uploads for form population

**Comment by sythel** [comment]
@elbfox 

URL to force an "Invalid Session"
http://shiny2.gsscdev.com/dams_mcda/

Will cause the "invalid session" but still allow you to use the application. I was able to upload prefs and then download successfully. All without django running (however I started django back up after verifying).


Let me know if we should get rid of, or text changes for the alert window that says the following
"Invalid Session. Cannot save or load results. You can continue to use. File uploads will still work."

**Comment by sythel** [comment]
issue open until we can verify it works for your development procedure

**Comment by elbfox** [comment]
Text change is helpful. The invalid session does not prevent development locally, it's just annoying/confusing for users. So, I think it's okay to close.
