### ISSUE TITLE
(New version with 12 criteria) File Upload Issue

### ISSUE THREAD

**Issue by sythel** [dams-mcda/Dams-MCDA#196]
I see what I did wrong. I tried to get rid of 2 decision criteria (move from 14 to 12) and then use the same test files on the shiny2 version (which I see now obviously wouldn't work). The problem is locally in the new DDST_v4 branch since I'm trying to cut down the set of decision criteria and everywhere else dimensions are specified from 14 to 12 columns.

**Edit:** Error code is as follows: 
`Warning: Error in <-: number of items to replace is not a multiple of replacement length
  74: WSM [WSM.R#157]
  73: generateOutput [C:\Users\Emma\Documents\R_ELF\R_NEST\MCDA_App_Shiny\MCDA_11042019\src\dams_mcda/server.R#1156]
  72: observeEventHandler [C:\Users\Emma\Documents\R_ELF\R_NEST\MCDA_App_Shiny\MCDA_11042019\src\dams_mcda/server.R#2027]
   1: shiny::runApp`

where WSM.R  line 157 is  `	AllDataMatrix[,,1] <- simplify2array(WestEnf_DataMatrix)`

_Originally posted by @elbfox in https://github.com/dams-mcda/Dams-MCDA/issues/190#issuecomment-635462178_

**Comment by sythel** [comment]
found the issue PR incoming

**Comment by elbfox** [comment]
Closing, because this appears resolved with the 12->13 required criteria
