### ISSUE TITLE
Group preference load modal

### ISSUE THREAD

**Issue by sythel** [dams-mcda/Dams-MCDA#200]
potential enhancement

as of right now if a participant revisits the site and loads preferences it reflects groups average and not their chosen preferences

in group load/new run modal
add ability to choose between loading groups average score or loading personal preferences from a prior saved group run

**Comment by sythel** [comment]
could only add this option if prior run exists. avoid confusing the user

**Comment by elbfox** [comment]
This seems fine to me if it's easy to do. Looks like you have it written already in #202, going to review that next.
