### ISSUE TITLE
Table download issue

### ISSUE THREAD

**Issue by elbfox** [dams-mcda/Dams-MCDA#204]
Sharon got the attached error when she tried to download the preference data table (Table 1) from the W. Enfield results page. 

Error did not open in a new tab, she had to click the back button and the model prompted her to start the program again. She could reload preferences using hte new feature but then had to go back through each page and scroll and click update before generating the result. Is there any way to fix that so it operates like the loading preferences from a file does where the tabs to the left are automatically green-text instead of red? She says it worked for Medway. 
![image](https://user-images.githubusercontent.com/19410104/83563339-f6e82b80-a4e8-11ea-900c-4b22aa2f1991.png)

**Comment by sythel** [comment]
fixed in #208
