### ISSUE TITLE
Citations

### ISSUE THREAD

**Issue by elbfox** [dams-mcda/Dams-MCDA#58]
Before release to the public, add to **Citations**:

- R
- Shiny
- ggplot2
- shinyjs
- Cairo

**Comment by elbfox** [comment]
Also (potentially) RColorBrewer, rgdal, spatstat, plotly

**Comment by sythel** [comment]
Django side of things
-------------------------
Python
Django
psycopg2
Postgres
django-rest-framework
django-filter

Other R libraries
-----------------------
rjson

**Comment by sythel** [comment]
should I work on this? add to current citations in "Acknowledgements" Tab? or new tab?

**Comment by elbfox** [comment]
Yes, if you have the full citation information handy, that would be most helpful! I accidentally continued updating within the DDST_v4 branch after merging, so that's where the most recent full citations list is, but I'm sure it won't be hard to merge our lists.

**Comment by elbfox** [comment]
I'm going to do another branch for this called "citations"...working on this locally now. I forgot about all of the R citations and focused on the academic publications instead. If you have info on Django etc. that would be helpful

**Comment by elbfox** [comment]
I added a software and programs section to sit below "Citations" in the "Acknowledgments" Tab and I'm getting an error that I can't figure out. 

`Warning in checkEncoding(file) :
  The input file C:\Users\Emma\Documents\R_ELF\R_NEST\MCDA_App_Shiny\MCDA_11042019\src\dams_mcda/ui.R does not seem to be encoded in UTF8
Warning in readLines(file, warn = FALSE) :
  invalid input found on input connection 'C:\Users\Emma\Documents\R_ELF\R_NEST\MCDA_App_Shiny\MCDA_11042019\src\dams_mcda/ui.R'
Error in parse(file, keep.source = FALSE, srcfile = src, encoding = enc) : 
  C:\Users\Emma\Documents\R_ELF\R_NEST\MCDA_App_Shiny\MCDA_11042019\src\dams_mcda/ui.R:1822:28: unexpected INCOMPLETE_STRING
1824:                            <br>Erich Neuwirth (2014). RColorBrewer: ColorBrewer Palettes. R package version 1.1-2. https://CRAN.R-project.org/package=RColorBrewer . <br>\
1825:                            <br>Hadley Wickham, Romain Fran
                                 ^
Warning: Error in sourceUTF8: Error sourcing C:\Users\Emma\AppData\Local\Temp\RtmpIBirSN\file3224548039a2
  [No stack trace available]`

I know only enough about R and Shiny to really get myself into trouble, it seems.

**Comment by sythel** [comment]
hanging quotes or a multi line missing a \ at the end?

**Comment by elbfox** [comment]
I don't think so, this is what it's tripping over:

`			 h2("Software and Programs Used (in alphabetical order)"),
			 HTML(
			   "Alex Couture-Beil (2018). rjson: JSON for R. R package version 0.2.20. https://CRAN.R-project.org/package=rjson . <br>\
			   <br>Dean Attali (2020). shinyjs: Easily Improve the User Experience of Your Shiny Apps in Seconds. R package version 1.1. https://CRAN.R-project.org/package=shinyjs . <br>\
			   <br>Erich Neuwirth (2014). RColorBrewer: ColorBrewer Palettes. R package version 1.1-2. https://CRAN.R-project.org/package=RColorBrewer . <br>\
			   <br>Hadley Wickham, Romain François, Lionel Henry and Kirill Müller (2018). dplyr: A Grammar of Data Manipulation. R package version 0.7.6. https://CRAN.R-project.org/package=dplyr . <br>\
			   <br>Hadley Wickham (2009). ggplot2: Elegant Graphics for Data Analysis. Springer-Verlag New York. <br>\
			   <br>Joe Cheng, Bhaskar Karambelkar and Yihui Xie (2019). leaflet: Create Interactive Web Maps with the JavaScript Leaflet Library. R package version 2.0.3. https://CRAN.R-project.org/package=leaflet . <br>\
			   <br>R Core Team (2017). R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. URL https://www.R-project.org/. <br>\
			   <br>RStudio Team (2015). RStudio: Integrated Development for R. RStudio, Inc., Boston, MA URL http://www.rstudio.com/. <br>\
			   <br>Simon Urbanek and Jeffrey Horner (2020). Cairo: R Graphics Device using Cairo Graphics Library for Creating High-Quality Bitmap (PNG, JPEG, TIFF), Vector (PDF, SVG, PostScript) and Display (X11 and Win32) Output.R package version 1.5-12. https://CRAN.R-project.org/package=Cairo . <br>\
			   <br>Tony Plate and Richard Heiberger (2016). abind: Combine Multidimensional Arrays. R package version 1.4-5. https://CRAN.R-project.org/package=abind . <br>\
			   <br>Winston Chang, Joe Cheng, JJ Allaire, Yihui Xie and Jonathan McPherson (2020). shiny: Web Application Framework for R. R package version 1.4.0.2. https://CRAN.R-project.org/package=shiny . <br>\
			   <br>Yihui Xie, Joe Cheng and Xianying Tan (2020). DT: A Wrapper of the JavaScript Library DataTables. R package version 0.13. https://CRAN.R-project.org/package=DT . <br>
			   "
			 )`

I don't notice anything that stands out , and the ui.R script had no issue with the other links I've added to the citations section

**Comment by sythel** [comment]
ç in line   
~~~
 <br>Hadley Wickham, Romain François, Lionel Henry and Kirill Müller (2018). dplyr: A Grammar of Data Manipulation. R package version 0.7.6. https://CRAN.R-project.org/package=dplyr . <br>\ 
~~~

**Comment by sythel** [comment]
and probably ü

**Comment by elbfox** [comment]
Yes! that's it, thank you.

**Comment by sythel** [comment]
"W\u00E4hrung" instead of "Währung"

try F\uC3BCranois for François 
try W\uC3A4hrung for Währung

**Comment by elbfox** [comment]
No, those don't seem to work. I got it to run by replacing François with Francois and Müller with Muller. That was the change I pushed just now in PR #203

**Comment by elbfox** [comment]
&#252; is the ü I'm still trying to find something for the ç

**Comment by sythel** [comment]
oops sent wrong one
~~~
&#231;
~~~

**Comment by sythel** [comment]
method if you need to find more

https://www.compart.com/en/unicode/U+00E7

under HTML Entity

**Comment by elbfox** [comment]
Great! Thank you! And thanks for your patience!

**Comment by sythel** [comment]
working on python software citations now.
