### ISSUE TITLE
Task 6 (Step 2: View Existing FERC Dam Map) WW

### ISSUE THREAD

**Issue by elbfox** [dams-mcda/Dams-MCDA#73]
Create hover link or box with "attribute list" of essential info for each dam in the map. Want people to be able to hover and see info Emma will provide in a box, like [this](https://www.google.com/maps/d/edit?hl=en&mid=1a9kpgGhdigYW7LuO0lmM6r-g3FQWK0xB&ll=44.90789535655622%2C-112.40178855000005&z=4).

GGplot2, maptools, rgdal packages in R. Emma to get existing fish habitat polygon from Sam.

**Comment by elbfox** [comment]
**Attribute List**

- Single or multi-dam development? S / M
- Power capacity (MW): 
- Average annual electricity generation (GWh):
- Date installed:

Please see attached file for list values specific to individual dams:
[Hover_DataTables_forMaps.xlsx](https://github.com/dams-mcda/Dams-MCDA/files/3383447/Hover_DataTables_forMaps.xlsx)

**Comment by sythel** [comment]
Will need latitude, longitude coordinates for each dam

**Comment by sythel** [comment]
reformatted the dam info file, blank cells for missing latitude/longitude

included 2 file formats

https://github.com/dams-mcda/Dams-MCDA/tree/format_map_data/dam_csv

**Comment by elbfox** [comment]
Map file will be .png, similar to the file on "View Existing Dams Map" in step two. Do you still need lat/long to place the hover tables? I can dig up that info, I'm just not sure where I have it saved off the top of my head, and if it's a png I'm not sure how lat/long will help.

**Comment by elbfox** [comment]
This is the newest version of the "View Existing Dams Map", and I will upload it along with the rest of them once I do a commit. I just wanted to give you a visual. The dams are all labeled on this map, so is it possible to link the data tables with the names?
![Penobscot_MO_14_0](https://user-images.githubusercontent.com/19410104/63616801-5b6b7700-c5b6-11e9-99b3-6747d0bd910b.png)

**Comment by elbfox** [comment]
Styling is fine for now. If Sharon disagrees, will reopen as a new aesthetic revision issue after 9/12.
