### ISSUE TITLE
Task 16 (Additional: Tracker indicator) WW

### ISSUE THREAD

**Issue by elbfox** [dams-mcda/Dams-MCDA#83]
Include duplicate tracker ("Progress for Alternative" 1.0/1.0) next to Update button on each dam page for people to see if they are working from a mobile device. It's clunky and irrelevant for desktop or laptop users, but it will be less annoying for mobile users.

**Comment by elbfox** [comment]
This has disappeared from my view in testing, but it may be because I'm testing the app locally on my laptop.

**Comment by sythel** [comment]
closing, now in master
