### ISSUE TITLE
Shoul we track Sam's Matlab source files?

### ISSUE THREAD

**Issue by sythel** [dams-mcda/Dams-MCDA#85]
Should we include sams sourcefiles in this repository?

for right now on branch matlab I have added them to .gitignore so they aren't included.

This is possibly important due to the repository being public at the moment

**Comment by elbfox** [comment]
Hi Billy, we should exclude Sam's files from the repository for now via .gitignore. Is it possible to add him as a collaborator at this time? We also need to add him to the developer list. This is something I'm happy to do after I meet with him next week and can discuss including sourcefiles and what he's like in his developer bio.

**Comment by elbfox** [comment]
FYI: I have added Sam as a collaborator. He says to keep the Matlab source files under .gitignore for now. 

MultiRank.m is the script that will be our 'source' in the Shiny App code and we are calling 'f' (which is 'outfull', referenced elsewhere, which is a 3D matrix with dam-specific alternative-criteria data) and 'pref' which is the preference data we are pulling from user inputs.

**Comment by sythel** [comment]
keeping matlab source in .gitignore
