### ISSUE TITLE
Run Matlab Successfully

### ISSUE THREAD

**Issue by sythel** [dams-mcda/Dams-MCDA#89]
Quoted from issue #85 

MultiRank.m is the script that will be our 'source' in the Shiny App code and we are calling 'f' (which is 'outfull', referenced elsewhere, which is a 3D matrix with dam-specific alternative-criteria data) and 'pref' which is the preference data we are pulling from user inputs.

**Comment by elbfox** [comment]
Notes for writing this in R are in the WSM.R script in the most recent merge with the master branch. Sam and I decided it would be easier to convert portions of MultiRank.m to R code (Sam added notes for this) and accomplish the 'scenario' (outfull = 3D matrix with dam-specific alternative-criteria data) preference weighting and ranking directly within WSM.R.

**Comment by sythel** [comment]
which functions will still be needed in matlab?

**Comment by elbfox** [comment]
It remains to be seen. If converting to R code is too tricky, then we may need to reconsider the original plan of sourcing from the MultiRank.m script.

**Comment by elbfox** [comment]
Closing issue, dealing with Matlab logic directly in WSM function and pulling from datasets/maps saved to repository.
