### ISSUE TITLE
TabsUpdate_Dams graphics issues WW

### ISSUE THREAD

**Issue by elbfox** [dams-mcda/Dams-MCDA#92]
Graphic issues in this branch need to be resolved. I think I may have confused the flow of the buttons by adding additional results tabs for the updated structure. @sythel could you please look over the new tabs for input/output flow? 

Results tabs for each dam is supposed to have 3 graphs (so far) to depict results calculated the same way as in http://shiny.gsscdev.com/dams_mcda/ (again, so far) see server.R, ui.R

ALSO: Step1 tab has over-sized image of fish (not sure how to cut this down...) see ui.R

**Comment by sythel** [comment]
fixed image by adding width attribute

**Comment by sythel** [comment]
removed 

> Please login with a username (email address) and a password.

due to the new layout will require login before they reach thispage

**Comment by sythel** [comment]
I see 8 enter preferences tabs and 8 results tabs. I don't see the problem mentioned.

**Comment by elbfox** [comment]
Slider input doesn't create graphic output, from what I can tell in my local test version of the app. I'm just running the app without the server for testing. The output tabs are there but the results graphs don't appear (even if they would be wrong, at this stage). Do they appear for you?

Also, I did some work on this after I highlighted the issue and may have commented out the fish image because it was distracting, but it should still be in the code. When you run the script, the fish image shows up HUGE in the first tab.

**Comment by sythel** [comment]
image fixed see comment or commit reference above

**Comment by sythel** [comment]
are [lines 588-606 still needed?](https://github.com/dams-mcda/Dams-MCDA/blob/2251d1f6b13bac43a1f8ccb9dfce8a0146487592/src/dams_mcda/server.R#L588)

**Comment by elbfox** [comment]
Potentially. I kept them in because I thought we would need to refer to the decision alternatives separately in printing the results graphs. Sam Roy sent a zip file with 3D matrix changes that I need to review and commit, so I'll take the lines out if he calls the alternatives some other way.

**Comment by sythel** [comment]
will need to revert the removal of https://github.com/dams-mcda/Dams-MCDA/commit/9de516d2ff5ad49b73e39e093ea93b391c48ee61#diff-808283fc76a538e4aaeb6138cb9e5f71L36 server.R line 36, I will do it in my branch

**Comment by sythel** [comment]
update buttons and progress now working again, will look into results next

**Comment by elbfox** [comment]
thank you!

**Comment by sythel** [comment]
error in server.R 

> Warning: Error in unlist: object 'r' not found
> shiny_server_1  |   74: unlist
> shiny_server_1  |   73: generateOutput [/srv/shiny-server/dams_mcda/server.R#746]
> shiny_server_1  |   72: observeEventHandler [/srv/shiny-server/dams_mcda/server.R#1669]
> shiny_server_1  |    1: runApp

r is not defined [here](https://github.com/dams-mcda/Dams-MCDA/blob/2251d1f6b13bac43a1f8ccb9dfce8a0146487592/src/dams_mcda/server.R#L583)

**Comment by elbfox** [comment]
lines 588- 606 can be commented out for now

**Comment by sythel** [comment]
if I change r to q in the quoted link:

Warning: Error in data.frame: row names supplied are of the wrong length

seems that the for loop needs debug/fixing

> error in server.R
> 
> > Warning: Error in unlist: object 'r' not found
> > shiny_server_1  |   74: unlist
> > shiny_server_1  |   73: generateOutput [/srv/shiny-server/dams_mcda/server.R#746]
> > shiny_server_1  |   72: observeEventHandler [/srv/shiny-server/dams_mcda/server.R#1669]
> > shiny_server_1  |    1: runApp
> 
> r is not defined [here](https://github.com/dams-mcda/Dams-MCDA/blob/2251d1f6b13bac43a1f8ccb9dfce8a0146487592/src/dams_mcda/server.R#L583)

**Comment by sythel** [comment]
dam 2d array values fixed in next commit.

generate output seems to have problems with data and graphs

**Comment by sythel** [comment]
@elbfox 

> Results tabs for each dam is supposed to have 3 graphs
graph1: same as before but only for dam instead of alternative (shows raw scores)
graph2: same as before but only for dam instead of alternative (shows total raw score composition)
graph3: graph with MCDA scores? one dam or all dams?

**Comment by elbfox** [comment]
Hi, graphs description quoted in [Task 13](https://github.com/dams-mcda/Dams-MCDA/issues/80#issue-454389236).  

There will be a "multi-dam" results tab with the WSM results for all dams (after Sam's MOGA code, which looks at all dams in the 3d matrix. I haven't added this yet. I am going to spend time on this tomorrow.

**Comment by elbfox** [comment]
I am getting this error when I try to run the app for testing: Warning: Error in <Anonymous>: No handler registered for type .clientdata_output_Step 1: Start Here_hidden
Stack trace (innermost first):
    1: runApp
Error in (function (name, val, shinysession)  : 
  No handler registered for type .clientdata_output_Step 1: Start Here_hidden

I don't know that output this means because Step 1 is just text and the fish image right now

**Comment by sythel** [comment]
fixed in master

**Comment by sythel** [comment]
think it has to do with htmlOutput tag

**Comment by elbfox** [comment]
thank you! I'm still struggling with understanding the input/output connection in Shiny.
